In [1]:
import numpy as np
arr = np.array([2,3,4,5])

In [2]:
print(arr.dtype)

int64


In [4]:
arr2=np.array(["banana","icecream","orange"])
print(arr2.dtype)

<U8


In [6]:
arr = np.array([0.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)

[0 2 3]


In [7]:
newlyarr = newarr.astype(bool)
print(newlyarr)

[False  True  True]


In [9]:
news = newlyarr.astype('U')
print(news)

['False' 'True' 'True']


In [10]:
#copy vs view in numpy
"""The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view."""

'The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.\n\nThe copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.\n\nThe view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.'

In [12]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
x[2] = 99
print(arr)
print(x)

[42  2  3  4  5]
[ 1  2 99  4  5]


In [14]:
y = x.view()
x[3] = 55
y[4] = 88
print(x,y)

[ 1  2 99 55 88] [ 1  2 99 55 88]


In [15]:
#checking the base 
print(x.base)
print(y.base)

None
[ 1  2 99 55 88]


In [18]:
arr = np.array([[1,2,3,4,5],[1,2,3,8,9]])
print(arr.shape)

(2, 5)


In [19]:
#reshaping 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#4 arrays , each with 3 elements
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
newarr = newarr.reshape(-1)

print(newarr)

[1 2 3 4 5 6 7 8]


In [22]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [23]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
